name: Preflight

on:
  pull_request:
    branches:
      - main

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: yarn --frozen-lockfile
      - name: Preflight
        run: yarn preflight
