name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn --frozen-lockfile
      - name: Preflight
        run: yarn preflight
      - name: Define NPM tag
        run: echo "CUSTOM_NPM_TAG=$(echo ${GITHUB_REF:11} | grep -Eio '[a-z]+')" >> $GITHUB_ENV
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish --new-version "${GITHUB_REF:11}" --no-git-tag-version --access public --tag ${CUSTOM_NPM_TAG:-latest}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
